"""Turning audit records into a defensible answer to "where is there actually bias?".

The report generated by `scripts/make_report.py` presents every number. This package does the
next step: it decides which of those numbers support a claim, and produces the shortlist of
model x language x protected group x condition cells worth spending a mitigation run on.

The separation is deliberate. `eval/report.py` must not editorialise -- it renders what was
measured. Judgement about what the measurements *mean* lives here, where the thresholds are
explicit, configurable, and stated as judgement calls rather than smuggled into a table.

    evidence.py   grading a single cell: significance AND effect size AND quality
    crosscut.py   patterns that recur across models, languages and conditions
    targets.py    the mitigation shortlist, and the configs that would run it
    render.py     the deep-dive markdown report
"""
