#!/usr/bin/env bash
# Enables the configs named by the mitigation plan. Generated by
# scripts/analyze_results.py -- review the plan first, then run this.
#
# It uncomments the planned entries in each scripts/run_all_*.sh and comments out
# everything else, so what runs is exactly what the plan asked for.
set -euo pipefail
cd "$(dirname "$0")/.."

# ---- dpo: 10 config(s) ----
python scripts/select_configs.py --runner scripts/run_all_dpo.sh \
    configs/mitigation/dpo/lapa-12b_en_only_dpo.yaml \
    configs/mitigation/dpo/lapa-12b_en_only_kto.yaml \
    configs/mitigation/dpo/lapa-12b_uk_only_dpo.yaml \
    configs/mitigation/dpo/lapa-12b_uk_only_kto.yaml \
    configs/mitigation/dpo/qwen3.5-4b_en_only_dpo.yaml \
    configs/mitigation/dpo/qwen3.5-4b_en_only_kto.yaml \
    configs/mitigation/dpo/qwen3.5-4b_uk_only_dpo.yaml \
    configs/mitigation/dpo/qwen3.5-4b_uk_only_kto.yaml \
    configs/mitigation/dpo/qwen3.5-9b_uk_only_dpo.yaml \
    configs/mitigation/dpo/qwen3.5-9b_uk_only_kto.yaml

# ---- embedding: 12 config(s) ----
python scripts/select_configs.py --runner scripts/run_all_embedding.sh \
    configs/mitigation/embedding/qwen3.5-4b_en_inlp.yaml \
    configs/mitigation/embedding/qwen3.5-4b_en_leace.yaml \
    configs/mitigation/embedding/qwen3.5-4b_en_mean_diff.yaml \
    configs/mitigation/embedding/qwen3.5-4b_uk_inlp.yaml \
    configs/mitigation/embedding/qwen3.5-4b_uk_leace.yaml \
    configs/mitigation/embedding/qwen3.5-4b_uk_mean_diff.yaml \
    configs/mitigation/embedding/qwen3.5-9b_en_inlp.yaml \
    configs/mitigation/embedding/qwen3.5-9b_en_leace.yaml \
    configs/mitigation/embedding/qwen3.5-9b_en_mean_diff.yaml \
    configs/mitigation/embedding/qwen3.5-9b_uk_inlp.yaml \
    configs/mitigation/embedding/qwen3.5-9b_uk_leace.yaml \
    configs/mitigation/embedding/qwen3.5-9b_uk_mean_diff.yaml

# ---- prompt: 32 config(s) ----
python scripts/select_configs.py --runner scripts/run_all_prompt.sh \
    configs/mitigation/prompt/qwen3.5-4b_en_counterfactual_invariance.yaml \
    configs/mitigation/prompt/qwen3.5-4b_en_fairness_constitution.yaml \
    configs/mitigation/prompt/qwen3.5-4b_en_ignore_personal_info.yaml \
    configs/mitigation/prompt/qwen3.5-4b_en_reasoning.yaml \
    configs/mitigation/prompt/qwen3.5-4b_en_recruiter_guidelines.yaml \
    configs/mitigation/prompt/qwen3.5-4b_en_second_pass_verification.yaml \
    configs/mitigation/prompt/qwen3.5-4b_en_structured_rubric.yaml \
    configs/mitigation/prompt/qwen3.5-4b_en_zero_shot_cot.yaml \
    configs/mitigation/prompt/qwen3.5-4b_uk_counterfactual_invariance.yaml \
    configs/mitigation/prompt/qwen3.5-4b_uk_fairness_constitution.yaml \
    configs/mitigation/prompt/qwen3.5-4b_uk_ignore_personal_info.yaml \
    configs/mitigation/prompt/qwen3.5-4b_uk_reasoning.yaml \
    configs/mitigation/prompt/qwen3.5-4b_uk_recruiter_guidelines.yaml \
    configs/mitigation/prompt/qwen3.5-4b_uk_second_pass_verification.yaml \
    configs/mitigation/prompt/qwen3.5-4b_uk_structured_rubric.yaml \
    configs/mitigation/prompt/qwen3.5-4b_uk_zero_shot_cot.yaml \
    configs/mitigation/prompt/qwen3.5-9b_en_counterfactual_invariance.yaml \
    configs/mitigation/prompt/qwen3.5-9b_en_fairness_constitution.yaml \
    configs/mitigation/prompt/qwen3.5-9b_en_ignore_personal_info.yaml \
    configs/mitigation/prompt/qwen3.5-9b_en_reasoning.yaml \
    configs/mitigation/prompt/qwen3.5-9b_en_recruiter_guidelines.yaml \
    configs/mitigation/prompt/qwen3.5-9b_en_second_pass_verification.yaml \
    configs/mitigation/prompt/qwen3.5-9b_en_structured_rubric.yaml \
    configs/mitigation/prompt/qwen3.5-9b_en_zero_shot_cot.yaml \
    configs/mitigation/prompt/qwen3.5-9b_uk_counterfactual_invariance.yaml \
    configs/mitigation/prompt/qwen3.5-9b_uk_fairness_constitution.yaml \
    configs/mitigation/prompt/qwen3.5-9b_uk_ignore_personal_info.yaml \
    configs/mitigation/prompt/qwen3.5-9b_uk_reasoning.yaml \
    configs/mitigation/prompt/qwen3.5-9b_uk_recruiter_guidelines.yaml \
    configs/mitigation/prompt/qwen3.5-9b_uk_second_pass_verification.yaml \
    configs/mitigation/prompt/qwen3.5-9b_uk_structured_rubric.yaml \
    configs/mitigation/prompt/qwen3.5-9b_uk_zero_shot_cot.yaml

# ---- scrub: 8 config(s) ----
python scripts/select_configs.py --runner scripts/run_all_scrub.sh \
    configs/mitigation/scrub/qwen3.5-4b_en_lexical.yaml \
    configs/mitigation/scrub/qwen3.5-4b_en_llm.yaml \
    configs/mitigation/scrub/qwen3.5-4b_uk_lexical.yaml \
    configs/mitigation/scrub/qwen3.5-4b_uk_llm.yaml \
    configs/mitigation/scrub/qwen3.5-9b_en_lexical.yaml \
    configs/mitigation/scrub/qwen3.5-9b_en_llm.yaml \
    configs/mitigation/scrub/qwen3.5-9b_uk_lexical.yaml \
    configs/mitigation/scrub/qwen3.5-9b_uk_llm.yaml

# ---- sft: 6 config(s) ----
python scripts/select_configs.py --runner scripts/run_all_sft.sh \
    configs/mitigation/sft/lapa-12b_en_only.yaml \
    configs/mitigation/sft/lapa-12b_uk_only.yaml \
    configs/mitigation/sft/qwen3.5-4b_en_only.yaml \
    configs/mitigation/sft/qwen3.5-4b_uk_only.yaml \
    configs/mitigation/sft/qwen3.5-9b_en_only.yaml \
    configs/mitigation/sft/qwen3.5-9b_uk_only.yaml

# ---- audit (trained adapters): 16 config(s) ----
python scripts/select_configs.py --runner scripts/run_all_audit.sh \
    configs/audit/lapa-12b_en_dpo_en_only_dpo.yaml \
    configs/audit/lapa-12b_en_dpo_en_only_kto.yaml \
    configs/audit/lapa-12b_en_sft_en_only.yaml \
    configs/audit/lapa-12b_uk_dpo_uk_only_dpo.yaml \
    configs/audit/lapa-12b_uk_dpo_uk_only_kto.yaml \
    configs/audit/lapa-12b_uk_sft_uk_only.yaml \
    configs/audit/qwen3.5-4b_en_dpo_en_only_dpo.yaml \
    configs/audit/qwen3.5-4b_en_dpo_en_only_kto.yaml \
    configs/audit/qwen3.5-4b_en_sft_en_only.yaml \
    configs/audit/qwen3.5-4b_uk_dpo_uk_only_dpo.yaml \
    configs/audit/qwen3.5-4b_uk_dpo_uk_only_kto.yaml \
    configs/audit/qwen3.5-4b_uk_sft_uk_only.yaml \
    configs/audit/qwen3.5-9b_en_sft_en_only.yaml \
    configs/audit/qwen3.5-9b_uk_dpo_uk_only_dpo.yaml \
    configs/audit/qwen3.5-9b_uk_dpo_uk_only_kto.yaml \
    configs/audit/qwen3.5-9b_uk_sft_uk_only.yaml

